Repository canonical/tmate-ssh-server-operator, pull requests merged in 2025-02, with the labels that each got.

#20 fix: Lint error in test code due to wrong type
  tests/unit/test_tmate.py
Labels: trivial, Libraries: Out of sync

#17 update readme
  README.md
Labels: documentation, trivial, Libraries: Out of sync

#19 docs: Add charm architecture documentation
  docs/explanation/charm-architecture.md
Labels: documentation, Libraries: Out of sync
